####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
# It uses a distroless base image for minimal attack surface.
#
# Before building the container image run:
#
# ./gradlew build -Dquarkus.native.enabled=true
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native-distroless -t revet-documents-api-native .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 revet-documents-api-native
#
###
FROM quay.io/quarkus/quarkus-distroless-image:2.0
COPY --chmod=755 build/*-runner /application

EXPOSE 8080
USER nonroot

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
